export enum Sector {
  Technology = 'Technology',
  CommunicationServices = 'Communication Services',
  ConsumerCyclical = 'Consumer Cyclical',
  Healthcare = 'Healthcare',
  FinancialServices = 'Financial Services',
  Industrials = 'Industrials',
  BasicMaterials = 'Basic Materials',
  ConsumerDefensive = 'Consumer Defensive',
  RealEstate = 'Real Estate',
  Utilities = 'Utilities',
  Energy = 'Energy',
}

export enum Industry {
  SoftwareApplication = 'Software - Application',
  InternetContentInformation = 'Internet Content & Information',
  SemiconductorEquipmentMaterials = 'Semiconductor Equipment & Materials',
  SoftwareInfrastructure = 'Software - Infrastructure',
  SpecialtyIndustrialMachinery = 'Specialty Industrial Machinery',
  BanksRegional = 'Banks - Regional',
  BanksDiversified = 'Banks - Diversified',
  BanksMoneyCenters = 'Banks - Money Center',
  AssetManagement = 'Asset Management',
  InsuranceLife = 'Insurance - Life',
  MedicalDevices = 'Medical Devices',
  DiagnosticsResearch = 'Diagnostics & Research',
  Biotechnology = 'Biotechnology',
  HealthcarePlans = 'Healthcare Plans',
  CreditServices = 'Credit Services',
  CapitalMarkets = 'Capital Markets',
  InsurancePropertyCasualty = 'Insurance - Property & Casualty',
  InsuranceSpecialty = 'Insurance - Specialty',
  AerospaceDefense = 'Aerospace & Defense',
  FarmConstructionMachinery = 'Farm & Construction Machinery',
  SpecialtyChemicals = 'Specialty Chemicals',
  ChemicalsSpecialty = 'Chemicals - Specialty',
  ChemicalsAgricultural = 'Chemicals - Agricultural',
  ResidentialConstruction = 'Residential Construction',
  BuildingProductsEquipment = 'Building Products & Equipment',
  ResidentialMortgageREITs = 'Residential Mortgage REITs',
  REITsDiversified = 'REITs - Diversified',
  REITsHealthcare = 'REITs - Healthcare',
  REITsIndustrial = 'REITs - Industrial',
  REITsOffice = 'REITs - Office',
  REITsResidential = 'REITs - Residential',
  REITsRetail = 'REITs - Retail',
  REITsSpecialty = 'REITs - Specialty',
  REITsHotelMotel = 'REITs - Hotel & Motel',
  REITsMortgage = 'REITs - Mortgage',
  REITsSelfStorage = 'REITs - Self Storage',
  REITsShoppingCenters = 'REITs - Shopping Centers',
  REITsIndustrialWarehouses = 'REITs - Industrial Warehouses',
  REITsHealthcareFacilities = 'REITs - Healthcare Facilities',
  REITsResortsCasinos = 'REITs - Resorts & Casinos',
  REITsDataCenters = 'REITs - Data Centers',
}
