name: 'Get & Cache Dependencies'
description: 'Get & Cache Dependencies(via npm) for faster builds'
runs:
  using: 'composite'
  steps:
    - name: 'Cache Dependencies'
      uses: 'actions/cache@v3'
      id: cache-node-modules
      with:
        path: |
          node_modules
          packages/**/node_modules
        key: deps-node-modules-${{ hashFiles('**/yarn-lock.json') }}

    - name: Install Dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn --frozen-lockfile
      # the shell to be used is required in composite custom actions
      shell: bash
