name: CI/CD

on:
  push:
    paths:
      - 'packages/frontend/**'
      - 'packages/backend/**'
      - 'packages/infra/**'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.17.1

      - name: Install Dependencies
        run: yarn


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

  #  frontend_test:
  #    needs: setup
  #    runs-on: ubuntu-latest
  #    steps:
  #      - name: Checkout Repo
  #        uses: actions/checkout@v2
  #
  #      - name: Test Frontend
  #        if: contains(github.event.head_commit.message, 'frontend')
  #        run: lerna run test --scope=@monorepo/frontend

  frontend_deploy:
    needs: setup # frontend_test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Build React App
        if: contains(github.event.head_commit.message, 'frontend')
        working-directory: ./packages/frontend
        run: yarn build
      - name: Deploy app build to S3 bucket
        if: contains(github.event.head_commit.message, 'frontend')
        working-directory: ./packages/frontend
        run: aws s3 sync ./dist/ s3://${{vars.FRONTEND_STORAGE_S3_BUCKET_NAME }} --acl public-read --delete

    #  backend_test:
    #    needs: setup
    #    runs-on: ubuntu-latest
    #    steps:
    #      - name: Checkout Repo
    #        uses: actions/checkout@v2
    #
    #      - name: Test Backend
    #        if: contains(github.event.head_commit.message, 'backend')
    #        run: lerna run test --scope=@monorepo/backend
    #
    #  backend_deploy:
    #    needs: backend_test
    #    runs-on: ubuntu-latest
    #    steps:
    #      - name: Checkout Repo
    #        uses: actions/checkout@v2
    #
    #      - name: Deploy Backend
    #        if: contains(github.event.head_commit.message, 'backend')
    #        run: lerna run deploy --scope=@monorepo/backend
    #
    #  infra_deploy:
    #    needs: setup
    #    runs-on: ubuntu-latest
    #    steps:
    #      - name: Checkout Repo
    #        uses: actions/checkout@v2
    #
    #      - name: Deploy Infra
    #        if: contains(github.event.head_commit.message, 'infra')
    #        run: lerna run deploy --scope=@monorepo/infra
    #
    #      - name: Deploy Frontend
    #        if: contains(github.event.head_commit.message, 'infra')
    #        run: lerna run deploy --scope=@monorepo/frontend
    #
    #      - name: Deploy Backend
    #        if: contains(github.event.head_commit.message, 'infra')
    #        run: lerna run deploy --scope=@monorepo/backend


